<?xml version="1.0" encoding="utf-8"?><Database Name="QLSV_BlockChain" Class="BlockChain_QLSVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LETRUONGQUOCTHI;Initial Catalog=QLSV_BlockChain;User ID=sa;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLSV_BlockChainConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaiKhoan" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaVaiTro" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoE" Type="System.String" DbType="Char(500)" CanBeNull="true" />
      <Column Name="SoN" Type="System.String" DbType="Char(500)" CanBeNull="true" />
      <Association Name="VaiTro_NguoiDung" Member="VaiTro" ThisKey="MaVaiTro" OtherKey="MaVaiTro" Type="VaiTro" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VaiTro" Member="VaiTros">
    <Type Name="VaiTro">
      <Column Name="MaVaiTro" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenVaiTro" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Thongtinkhoa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="VaiTro_NguoiDung" Member="NguoiDungs" ThisKey="MaVaiTro" OtherKey="MaVaiTro" Type="NguoiDung" />
    </Type>
  </Table>
  <Table Name="dbo.KhoaVien" Member="KhoaViens">
    <Type Name="KhoaVien">
      <Column Name="IDKhoa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKhoa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="KhoaVien_SinhVien" Member="SinhViens" ThisKey="IDKhoa" OtherKey="KhoaVien" Type="SinhVien" />
    </Type>
  </Table>
  <Table Name="dbo.StatusSinhVien" Member="StatusSinhViens">
    <Type Name="StatusSinhVien">
      <Column Name="IDTrangThai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTrangThai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AllowEdit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="StatusSinhVien_SinhVien" Member="SinhViens" ThisKey="IDTrangThai" OtherKey="TrangThai" Type="SinhVien" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="IDSinhVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSinhVien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="KhoaVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KhoaVien_SinhVien" Member="KhoaVien1" ThisKey="KhoaVien" OtherKey="IDKhoa" Type="KhoaVien" IsForeignKey="true" />
      <Association Name="StatusSinhVien_SinhVien" Member="StatusSinhVien" ThisKey="TrangThai" OtherKey="IDTrangThai" Type="StatusSinhVien" IsForeignKey="true" />
    </Type>
  </Table>
</Database>